databases:
  - name: shumyyy_DB
    databaseName: shumyyy_db
    user: shumyyy
    region: singapore

services:
  - type: web
    name: shumyyy
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shumyyy_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
